Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : ARNALDO
// Descrição   : faca um programa que calcula a tabuada de qualquer numero
// Autor(a)    : RUAN
// Data atual  : 16/11/2017
Var
// Seção de Declarações das variáveis 
contador,xablau:inteiro


Inicio
  repita
  escreva("digite um numero inteiro: ")
 xablau<-1
  para xablau de 1 ate 1000 passo 1 faca
  escreval(contador+xablau)
  fimpara


Fimalgoritmo
