Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/11/2017
Var
// Seção de Declarações das variáveis 
num:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
num<-1
repita
escreval(num)
num<- num+1
ate(num>10000)


Fimalgoritmo